In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [37]:
import pandas as pd
cancer = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data')
cancer.columns=['ID', 'Clump_Thickness', 'U_Cell_Size', 'U_Cell_Shape','Marg_Adhes', 'Epi_Cell_Size', 'Bare_Nuc', 'Chromatin', 'Nucleoli','Mitoses', 'Class']
cancer = cancer[~((cancer['Bare_Nuc'] == '?' ))].astype(int)
cols=['Clump_Thickness', 'U_Cell_Size', 'U_Cell_Shape','Marg_Adhes', 'Epi_Cell_Size', 'Bare_Nuc', 'Chromatin', 'Nucleoli','Mitoses']
cancer.head()
cancer.astype(int)

,ID,Clump_Thickness,U_Cell_Size,U_Cell_Shape,Marg_Adhes,Epi_Cell_Size,Bare_Nuc,Chromatin,Nucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
5,1018099,1,1,1,1,2,10,3,1,1,2
6,1018561,2,1,2,1,2,1,3,1,1,2
7,1033078,2,1,1,1,2,1,1,1,5,2
8,1033078,4,2,1,1,2,1,2,1,1,2
9,1035283,1,1,1,1,1,1,3,1,1,2
10,1036172,2,1,1,1,2,1,2,1,1,2
11,1041801,5,3,3,3,2,3,4,4,1,4
12,1043999,1,1,1,1,2,3,3,1,1,2
13,1044572,8,7,5,10,7,9,5,5,4,4
14,1047630,7,4,6,4,6,1,4,3,1,4
15,1048672,4,1,1,1,2,1,2,1,1,2
16,1049815,4,1,1,1,2,1,3,1,1,2
17,1050670,10,7,7,6,4,10,4,1,2,4
18,1050718,6,1,1,1,2,1,3,1,1,2
19,1054590,7,3,2,10,5,10,5,4,4,4
20,1054593,10,5,5,3,6,7,7,10,1,4
21,1056784,3,1,1,1,2,1,2,1,1,2
23,1059552,1,1,1,1,2,1,3,1,1,2
24,1065726,5,2,3,4,2,7,3,6,1,4
25,1066373,3,2,1,1,1,1,2,1,1,2
26,1066979,5,1,1,1,2,1,2,1,1,2
27,1067444,2,1,1,1,2,1,2,1,1,2
28,1070935,1,1,3,1,2,1,1,1,1,2
29,1070935,3,1,1,1,1,1,2,1,1,2
30,1071760,2,1,1,1,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
668,1350423,5,10,10,8,5,5,7,10,1,4
669,1352848,3,10,7,8,5,8,7,4,1,4
670,1353092,3,2,1,2,2,1,3,1,1,2
671,1354840,2,1,1,1,2,1,3,1,1,2
672,1354840,5,3,2,1,3,1,1,1,1,2
673,1355260,1,1,1,1,2,1,2,1,1,2
674,1365075,4,1,4,1,2,1,1,1,1,2
675,1365328,1,1,2,1,2,1,2,1,1,2
676,1368267,5,1,1,1,2,1,1,1,1,2
677,1368273,1,1,1,1,2,1,1,1,1,2
678,1368882,2,1,1,1,2,1,1,1,1,2
679,1369821,10,10,10,10,5,10,10,10,7,4
680,1371026,5,10,10,10,4,10,5,6,3,4
681,1371920,5,1,1,1,2,1,3,2,1,2
682,466906,1,1,1,1,2,1,1,1,1,2
683,466906,1,1,1,1,2,1,1,1,1,2
684,534555,1,1,1,1,2,1,1,1,1,2
685,536708,1,1,1,1,2,1,1,1,1,2
686,566346,3,1,1,1,2,1,2,3,1,2
687,603148,4,1,1,1,2,1,1,1,1,2
688,654546,1,1,1,1,2,1,1,1,8,2
689,654546,1,1,1,3,2,1,1,1,1,2
690,695091,5,10,10,5,4,5,4,4,1,4
691,714039,3,1,1,1,2,1,1,1,1,2
692,763235,3,1,1,1,2,1,2,1,2,2
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [38]:
cancer.head()

,ID,Clump_Thickness,U_Cell_Size,U_Cell_Shape,Marg_Adhes,Epi_Cell_Size,Bare_Nuc,Chromatin,Nucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4

In [40]:
X1 = cancer.loc[cancer['Class'] == 2]
X2 = cancer.loc[cancer['Class'] == 4]
X1_1 = X1.iloc[0:, [1,5]].values
X1_2 = X2.iloc[0:, [1,5]].values

In [41]:
type(X1_1.tolist())

list

In [50]:
arr1=list()
for line in X1_1:
    line = list(line)
    arr1.append(line)
arr2=list()
for line in X1_2:
    line = list(line)
    arr2.append(line)

In [51]:
arr1

[[5, 7],
 [3, 2],
 [6, 3],
 [4, 2],
 [1, 2],
 [2, 2],
 [2, 2],
 [4, 2],
 [1, 1],
 [2, 2],
 [1, 2],
 [4, 2],
 [4, 2],
 [6, 2],
 [3, 2],
 [1, 2],
 [3, 1],
 [5, 2],
 [2, 2],
 [1, 2],
 [3, 1],
 [2, 2],
 [2, 2],
 [3, 2],
 [2, 2],
 [6, 1],
 [1, 2],
 [1, 2],
 [4, 2],
 [1, 2],
 [1, 2],
 [4, 2],
 [1, 2],
 [5, 2],
 [1, 2],
 [1, 2],
 [1, 2],
 [5, 2],
 [3, 2],
 [2, 3],
 [2, 1],
 [4, 2],
 [5, 2],
 [3, 2],
 [4, 2],
 [2, 3],
 [1, 2],
 [3, 2],
 [4, 2],
 [1, 2],
 [2, 2],
 [1, 2],
 [2, 2],
 [5, 2],
 [4, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [1, 2],
 [8, 2],
 [1, 4],
 [3, 2],
 [1, 2],
 [4, 2],
 [1, 2],
 [3, 2],
 [1, 10],
 [5, 2],
 [2, 2],
 [3, 2],
 [3, 3],
 [5, 2],
 [4, 2],
 [3, 2],
 [4, 2],
 [3, 2],
 [2, 2],
 [1, 2],
 [2, 2],
 [1, 3],
 [3, 8],
 [1, 1],
 [4, 2],
 [1, 2],
 [1, 2],
 [2, 2],
 [4, 2],
 [3, 2],
 [1, 1],
 [4, 2],
 [3, 2],
 [1, 1],
 [3, 2],
 [1, 2],
 [1, 2],
 [2, 2],
 [4, 2],
 [1, 1],
 [1, 2],
 [6, 2],
 [2, 1],
 [1, 2],
 [5, 2],
 [1, 2],
 [3, 2],
 [4, 2],
 [8, 4],
 [5, 2],
 [1, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [1, 2],
 [1, 1],
 [1, 1],
 [5, 1],
 [1, 2],
 [1, 2],
 [1, 2],
 [6, 2],
 [1, 2],
 [1, 2],
 [1, 1],
 [8, 3],
 [3, 3],
 [5, 2],
 [3, 1],
 [2, 2],
 [1, 2],
 [1, 2],
 [5, 2],
 [4, 2],
 [1, 2],
 [6, 3],
 [3, 2],
 [3, 2],
 [3, 2],
 [5, 5],
 [5, 2],
 [1, 2],
 [5, 2],
 [3, 2],
 [3, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [2, 2],
 [3, 3],
 [1, 2],
 [1, 2],
 [5, 4],
 [8, 5],
 [1, 2],
 [1, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [2, 3],
 [1, 2],
 [1, 2],
 [1, 1],
 [1, 5],
 [4, 6],
 [3, 2],
 [1, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [5, 2],
 [1, 2],
 [1, 2],
 [1, 1],
 [1, 2],
 [2, 2],
 [1, 2],
 [1, 2],
 [5, 3],
 [1, 1],
 [5, 2],
 [2, 2],
 [3, 7],
 [1, 2],
 [4, 3],
 [3, 4],
 [4, 2],
 [2, 2],
 [2, 2],
 [1, 2],
 [1, 1],
 [4, 3],
 [1, 2],
 [4, 2],
 [5, 2],
 [3, 2],
 [1, 2],
 [1, 2],
 [1, 1],
 [3, 3],
 [5, 4],
 [1, 2],
 [3, 2],
 [2, 2],
 [2, 2],
 [3, 3],
 [5, 3],
 [2, 2],
 [5, 3],
 [1, 2],
 [3, 2],
 [1, 1],
 [1, 2],
 [3, 2],
 [3, 2],
 [4, 2],
 [3, 2],
 [1, 2],
 [3, 2],
 [5, 2],
 [3, 2],
 [1, 2],
 [1, 2],
 [4, 2],
 [1, 2],
 [2, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [3, 3],
 [1, 2],
 [5, 2],
 [2, 5],
 [3, 2],
 [4, 2],
 [5, 2],
 [3, 2],
 [5, 2],
 [1, 2],
 [2, 2],
 [1, 2],
 [5, 4],
 [5, 2],
 [3, 2],
 [6, 5],
 [4, 2],
 [4, 2],
 [5, 2],
 [5, 2],
 [1, 2],
 [1, 2],
 [5, 3],
 [2, 2],
 [1, 2],
 [5, 2],
 [1, 1],
 [4, 1],
 [5, 2],
 [3, 2],
 [2, 3],
 [5, 2],
 [5, 2],
 [5, 2],
 [3, 2],
 [6, 2],
 [4, 2],
 [4, 2],
 [4, 2],
 [1, 2],
 [3, 1],
 [6, 2],
 [6, 1],
 [4, 2],
 [5, 2],
 [3, 2],
 [4, 2],
 [4, 2],
 [5, 2],
 [5, 1],
 [5, 2],
 [5, 2],
 [1, 1],
 [3, 1],
 [1, 2],
 [4, 1],
 [5, 4],
 [3, 1],
 [1, 1],
 [4, 2],
 [4, 2],
 [4, 2],
 [6, 2],
 [4, 2],
 [4, 2],
 [4, 2],
 [1, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [2, 2],
 [1, 2],
 [5, 2],
 [5, 2],
 [3, 1],
 [1, 1],
 [1, 1],
 [3, 2],
 [1, 3],
 [4, 3],
 [3, 2],
 [3, 2],
 [4, 2],
 [4, 2],
 [6, 2],
 [4, 1],
 [4, 2],
 [1, 1],
 [3, 2],
 [2, 2],
 [1, 2],
 [5, 2],
 [5, 2],
 [4, 2],
 [6, 2],
 [5, 2],
 [3, 2],
 [5, 2],
 [4, 2],
 [2, 2],
 [5, 2],
 [2, 1],
 [3, 1],
 [3, 2],
 [1, 2],
 [3, 2],
 [4, 2],
 [3, 2],
 [4, 2],
 [5, 1],
 [5, 2],
 [2, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [1, 2],
 [3, 2],
 [4, 2],
 [3, 2],
 [4, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [5, 2],
 [1, 2],
 [1, 2],
 [1, 2],
 [5, 2],
 [3, 2],
 [5, 3],
 [1, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [4, 2],
 [5, 2],
 [3, 2],
 [5, 1],
 [3, 2],
 [1, 1],
 [4, 2],
 [4, 2],
 [1, 2],
 [5, 2],
 [2, 2],
 [2, 1],
 [4, 2],
 [3, 2],
 [4, 2],
 [5, 2],
 [3, 2],
 [6, 3],
 [7, 2],
 [1, 2],
 [5, 1],
 [3, 3],
 [2, 2],
 [2, 2],
 [4, 2],
 [6, 2],
 [5, 2],
 [1, 2],
 [3, 2],
 [3, 2],
 [4, 2],
 [4, 2],
 [5, 2],
 [4, 2],
 [3, 2],
 [3, 2],
 [1, 2],
 [2, 2],
 [3, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [3, 3],
 [1, 2],
 [5, 2],
 [4, 2],
 [3, 2],
 [3, 2],
 [5, 2],
 [5, 8],
 [1, 2],
 [1, 2],
 [4, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [1, 2],
 [5, 2],
 [3, 2],
 [3, 2],
 [2, 2],
 [5, 3],
 [1, 2],
 [4, 2],
 [1, 2],
 [5, 2],
 [1, 2],
 [2, 2],
 [5, 2],
 [1, 2],
 [1, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [4, 2],
 [1, 2],
 [1, 2],
 [3, 2],
 [3, 2],
 [3, 3],
 [2, 2]]

In [52]:
dict={1:arr1,-1:arr2}

In [53]:
dict

{-1: [[8, 7],
  [5, 2],
  [8, 7],
  [7, 6],
  [10, 4],
  [7, 5],
  [10, 6],
  [5, 2],
  [10, 8],
  [10, 6],
  [5, 2],
  [2, 6],
  [10, 3],
  [6, 8],
  [5, 10],
  [10, 8],
  [3, 4],
  [7, 4],
  [9, 2],
  [5, 2],
  [10, 3],
  [5, 10],
  [10, 8],
  [10, 4],
  [8, 3],
  [8, 5],
  [5, 6],
  [9, 2],
  [5, 3],
  [9, 10],
  [6, 5],
  [10, 3],
  [5, 8],
  [8, 4],
  [6, 10],
  [9, 6],
  [10, 3],
  [3, 8],
  [5, 10],
  [3, 5],
  [3, 5],
  [9, 10],
  [7, 5],
  [10, 10],
  [2, 2],
  [8, 6],
  [10, 10],
  [7, 3],
  [10, 2],
  [1, 8],
  [6, 3],
  [8, 5],
  [10, 2],
  [10, 10],
  [4, 4],
  [10, 10],
  [5, 8],
  [5, 9],
  [7, 4],
  [8, 5],
  [5, 8],
  [9, 4],
  [3, 6],
  [8, 10],
  [7, 6],
  [10, 4],
  [5, 3],
  [9, 6],
  [10, 5],
  [5, 8],
  [10, 6],
  [6, 8],
  [8, 3],
  [5, 10],
  [5, 8],
  [5, 6],
  [5, 5],
  [8, 4],
  [1, 5],
  [10, 6],
  [5, 5],
  [10, 6],
  [7, 10],
  [9, 5],
  [10, 10],
  [5, 6],
  [10, 7],
  [8, 5],
  [8, 4],
  [10, 7],
  [10, 3],
  [8, 5],
  [6, 6],
  [10, 10],
  [4, 1],
  [7, 3],
  [10, 3],
  [10, 4],
  [8, 3],
  [10, 10],
  [7, 3],
  [6, 6],
  [10, 5],
  [10, 8],
  [9, 6],
  [8, 6],
  [10, 3],
  [8, 5],
  [8, 2],
  [10, 2],
  [6, 8],
  [9, 10],
  [5, 4],
  [10, 3],
  [5, 10],
  [8, 5],
  [10, 6],
  [7, 10],
  [10, 3],
  [3, 3],
  [10, 3],
  [8, 3],
  [3, 3],
  [7, 3],
  [10, 3],
  [1, 4],
  [10, 2],
  [7, 2],
  [8, 8],
  [10, 10],
  [6, 4],
  [5, 6],
  [10, 2],
  [5, 6],
  [9, 4],
  [8, 4],
  [10, 9],
  [8, 3],
  [10, 4],
  [7, 4],
  [8, 10],
  [5, 5],
  [6, 6],
  [7, 5],
  [5, 2],
  [10, 2],
  [8, 6],
  [10, 5],
  [10, 2],
  [5, 4],
  [8, 3],
  [6, 4],
  [8, 2],
  [10, 2],
  [7, 10],
  [3, 5],
  [4, 3],
  [2, 7],
  [5, 3],
  [8, 10],
  [8, 8],
  [10, 3],
  [6, 10],
  [3, 6],
  [6, 8],
  [5, 5],
  [10, 4],
  [7, 2],
  [10, 3],
  [3, 6],
  [10, 8],
  [8, 3],
  [8, 10],
  [10, 10],
  [9, 10],
  [8, 4],
  [10, 3],
  [10, 6],
  [10, 4],
  [5, 6],
  [4, 6],
  [10, 2],
  [10, 5],
  [8, 6],
  [10, 6],
  [10, 4],
  [6, 4],
  [4, 4],
  [9, 10],
  [8, 5],
  [10, 6],
  [3, 3],
  [6, 3],
  [5, 3],
  [5, 6],
  [8, 7],
  [6, 3],
  [4, 3],
  [4, 4],
  [10, 3],
  [7, 4],
  [7, 4],
  [6, 4],
  [7, 4],
  [5, 5],
  [8, 6],
  [10, 6],
  [8, 8],
  [7, 3],
  [10, 4],
  [5, 5],
  [6, 4],
  [8, 6],
  [9, 6],
  [4, 4],
  [2, 4],
  [10, 3],
  [4, 4],
  [5, 4],
  [5, 5],
  [10, 5],
  [5, 10],
  [10, 3],
  [5, 5],
  [8, 6],
  [4, 7],
  [8, 5],
  [10, 7],
  [5, 10],
  [7, 3],
  [5, 6],
  [5, 5],
  [3, 5],
  [10, 5],
  [5, 4],
  [5, 4],
  [5, 7],
  [4, 3],
  [4, 4]],
 1: [[5, 7],
  [3, 2],
  [6, 3],
  [4, 2],
  [1, 2],
  [2, 2],
  [2, 2],
  [4, 2],
  [1, 1],
  [2, 2],
  [1, 2],
  [4, 2],
  [4, 2],
  [6, 2],
  [3, 2],
  [1, 2],
  [3, 1],
  [5, 2],
  [2, 2],
  [1, 2],
  [3, 1],
  [2, 2],
  [2, 2],
  [3, 2],
  [2, 2],
  [6, 1],
  [1, 2],
  [1, 2],
  [4, 2],
  [1, 2],
  [1, 2],
  [4, 2],
  [1, 2],
  [5, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [5, 2],
  [3, 2],
  [2, 3],
  [2, 1],
  [4, 2],
  [5, 2],
  [3, 2],
  [4, 2],
  [2, 3],
  [1, 2],
  [3, 2],
  [4, 2],
  [1, 2],
  [2, 2],
  [1, 2],
  [2, 2],
  [5, 2],
  [4, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [1, 2],
  [8, 2],
  [1, 4],
  [3, 2],
  [1, 2],
  [4, 2],
  [1, 2],
  [3, 2],
  [1, 10],
  [5, 2],
  [2, 2],
  [3, 2],
  [3, 3],
  [5, 2],
  [4, 2],
  [3, 2],
  [4, 2],
  [3, 2],
  [2, 2],
  [1, 2],
  [2, 2],
  [1, 3],
  [3, 8],
  [1, 1],
  [4, 2],
  [1, 2],
  [1, 2],
  [2, 2],
  [4, 2],
  [3, 2],
  [1, 1],
  [4, 2],
  [3, 2],
  [1, 1],
  [3, 2],
  [1, 2],
  [1, 2],
  [2, 2],
  [4, 2],
  [1, 1],
  [1, 2],
  [6, 2],
  [2, 1],
  [1, 2],
  [5, 2],
  [1, 2],
  [3, 2],
  [4, 2],
  [8, 4],
  [5, 2],
  [1, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [1, 2],
  [1, 1],
  [1, 1],
  [5, 1],
  [1, 2],
  [1, 2],
  [1, 2],
  [6, 2],
  [1, 2],
  [1, 2],
  [1, 1],
  [8, 3],
  [3, 3],
  [5, 2],
  [3, 1],
  [2, 2],
  [1, 2],
  [1, 2],
  [5, 2],
  [4, 2],
  [1, 2],
  [6, 3],
  [3, 2],
  [3, 2],
  [3, 2],
  [5, 5],
  [5, 2],
  [1, 2],
  [5, 2],
  [3, 2],
  [3, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [2, 2],
  [3, 3],
  [1, 2],
  [1, 2],
  [5, 4],
  [8, 5],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [2, 3],
  [1, 2],
  [1, 2],
  [1, 1],
  [1, 5],
  [4, 6],
  [3, 2],
  [1, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [5, 2],
  [1, 2],
  [1, 2],
  [1, 1],
  [1, 2],
  [2, 2],
  [1, 2],
  [1, 2],
  [5, 3],
  [1, 1],
  [5, 2],
  [2, 2],
  [3, 7],
  [1, 2],
  [4, 3],
  [3, 4],
  [4, 2],
  [2, 2],
  [2, 2],
  [1, 2],
  [1, 1],
  [4, 3],
  [1, 2],
  [4, 2],
  [5, 2],
  [3, 2],
  [1, 2],
  [1, 2],
  [1, 1],
  [3, 3],
  [5, 4],
  [1, 2],
  [3, 2],
  [2, 2],
  [2, 2],
  [3, 3],
  [5, 3],
  [2, 2],
  [5, 3],
  [1, 2],
  [3, 2],
  [1, 1],
  [1, 2],
  [3, 2],
  [3, 2],
  [4, 2],
  [3, 2],
  [1, 2],
  [3, 2],
  [5, 2],
  [3, 2],
  [1, 2],
  [1, 2],
  [4, 2],
  [1, 2],
  [2, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [3, 3],
  [1, 2],
  [5, 2],
  [2, 5],
  [3, 2],
  [4, 2],
  [5, 2],
  [3, 2],
  [5, 2],
  [1, 2],
  [2, 2],
  [1, 2],
  [5, 4],
  [5, 2],
  [3, 2],
  [6, 5],
  [4, 2],
  [4, 2],
  [5, 2],
  [5, 2],
  [1, 2],
  [1, 2],
  [5, 3],
  [2, 2],
  [1, 2],
  [5, 2],
  [1, 1],
  [4, 1],
  [5, 2],
  [3, 2],
  [2, 3],
  [5, 2],
  [5, 2],
  [5, 2],
  [3, 2],
  [6, 2],
  [4, 2],
  [4, 2],
  [4, 2],
  [1, 2],
  [3, 1],
  [6, 2],
  [6, 1],
  [4, 2],
  [5, 2],
  [3, 2],
  [4, 2],
  [4, 2],
  [5, 2],
  [5, 1],
  [5, 2],
  [5, 2],
  [1, 1],
  [3, 1],
  [1, 2],
  [4, 1],
  [5, 4],
  [3, 1],
  [1, 1],
  [4, 2],
  [4, 2],
  [4, 2],
  [6, 2],
  [4, 2],
  [4, 2],
  [4, 2],
  [1, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [2, 2],
  [1, 2],
  [5, 2],
  [5, 2],
  [3, 1],
  [1, 1],
  [1, 1],
  [3, 2],
  [1, 3],
  [4, 3],
  [3, 2],
  [3, 2],
  [4, 2],
  [4, 2],
  [6, 2],
  [4, 1],
  [4, 2],
  [1, 1],
  [3, 2],
  [2, 2],
  [1, 2],
  [5, 2],
  [5, 2],
  [4, 2],
  [6, 2],
  [5, 2],
  [3, 2],
  [5, 2],
  [4, 2],
  [2, 2],
  [5, 2],
  [2, 1],
  [3, 1],
  [3, 2],
  [1, 2],
  [3, 2],
  [4, 2],
  [3, 2],
  [4, 2],
  [5, 1],
  [5, 2],
  [2, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [1, 2],
  [3, 2],
  [4, 2],
  [3, 2],
  [4, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [5, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [5, 2],
  [3, 2],
  [5, 3],
  [1, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [4, 2],
  [5, 2],
  [3, 2],
  [5, 1],
  [3, 2],
  [1, 1],
  [4, 2],
  [4, 2],
  [1, 2],
  [5, 2],
  [2, 2],
  [2, 1],
  [4, 2],
  [3, 2],
  [4, 2],
  [5, 2],
  [3, 2],
  [6, 3],
  [7, 2],
  [1, 2],
  [5, 1],
  [3, 3],
  [2, 2],
  [2, 2],
  [4, 2],
  [6, 2],
  [5, 2],
  [1, 2],
  [3, 2],
  [3, 2],
  [4, 2],
  [4, 2],
  [5, 2],
  [4, 2],
  [3, 2],
  [3, 2],
  [1, 2],
  [2, 2],
  [3, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [3, 3],
  [1, 2],
  [5, 2],
  [4, 2],
  [3, 2],
  [3, 2],
  [5, 2],
  [5, 8],
  [1, 2],
  [1, 2],
  [4, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [1, 2],
  [5, 2],
  [3, 2],
  [3, 2],
  [2, 2],
  [5, 3],
  [1, 2],
  [4, 2],
  [1, 2],
  [5, 2],
  [1, 2],
  [2, 2],
  [5, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [4, 2],
  [1, 2],
  [1, 2],
  [3, 2],
  [3, 2],
  [3, 3],
  [2, 2]]}